# CRUD para Citas

### Crear una cita
POST http://localhost:3001/api/appointments
Content-Type: application/json

{
    "date": "2024-11-22",
    "appointmentTime": "18:00",
    "realAppointmentTime": "15:00",
    "available": false,
    "appointment": {
        "confirmAppointment": false,
        "name": "Jane Doe",
        "reason": "Consultation"
    }
}

###

### Obtener todas las citas
GET http://localhost:3001/api/appointments

###

### Obtener citas por fecha
GET http://localhost:3001/api/appointments/date/2024-11-22

###

### Eliminar una cita
DELETE http://localhost:3001/api/appointments/2024-11-22/18:00

###

### Confirmar una cita
PUT http://localhost:3001/api/appointments/confirm/2
Content-Type: application/json

{
    "confirmAppointment": true
}

###

### Login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "usuarioEjemplo",
    "password": "contraseñaEjemplo",
    "role": "admin"
}
###
POST http://localhost:3001/api/register
Content-Type: application/json

{
    "username": "usuarioEjemplo",
    "password": "contraseñaEjemplo",
    "role": "admin"
}