# @variableName = variableValue
@host = localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMyNjk5OTEwLCJleHAiOjE3MzI3MDM1MTB9.QBiIh934CC1m-bIDk4kJd9do21tiNA91BfEJlBRsoBs
### Crear una cita
POST http://{{host}}/api/appointments
Content-Type: application/json
Authorization: token {{token}}

{
    "date": "2024-11-23",
    "appointmentTime": "8:00",
    "realAppointmentTime": "15:00",
    "available": true,
    "appointment": {
        "confirmAppointment": false,
        "name": "John Doe",
        "reason": "Consultation"
    }
}

###

### Obtener todas las citas
GET http://{{host}}/api/appointments
Authorization: token {{token}}

###

### Obtener citas por fecha
GET http://{{host}}/api/appointments/date/2024-11-22
Authorization: token {{token}}
###

### Eliminar una cita
DELETE http://{{{{host}}}}/api/appointments/2024-11-22/18:00
Authorization: token {{token}}
###

### Confirmar una cita
PUT http://{{host}}/api/appointments/confirm/3
Content-Type: application/json
Authorization: token {{token}}

{
    "confirmAppointment": true
}

###

### Login
POST http://{{host}}/api/auth/login
Content-Type: application/json
Authorization: token {{token}}

{
    "username": "usuarioEjemplo2",
    "password": "contraseñaEjemplo2",
    "role": "admin"
}
###
POST http://{{host}}/api/auth/register
Content-Type: application/json
Authorization: token {{token}}

{
    "username": "usuarioEjemplo2",
    "password": "contraseñaEjemplo2",
    "role": "admin"
}

###
GET http://{{host}}/api/appointments HTTP/1.1
Authorization: token {{token}}
