# @variableName = variableValue
@host = localhost:3001
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMjcxMDUwMywiZXhwIjoxNzMyNzE0MTAzfQ.BdhqntAakA7CZWpnjNiTPmr48UUgrsZ0QsZUh5fIkBI



### Crear una cita
POST http://{{host}}/api/appointments
Content-Type: application/json
Authorization: token {{token}}

{
    "date": "2024-11-23",
    "appointmentTime": "8:00",
    "realAppointmentTime": "15:00",
    "available": true,
    "appointment": {
        "confirmAppointment": false,
        "name": "John Doe",
        "reason": "Consultation"
    }
}

### Obtener todas las citas
GET http://{{host}}/api/appointments
Authorization: token {{token}}

###

### Obtener citas por fecha
GET http://{{host}}/api/appointments/date/2024-11-22
Authorization: token {{token}}
###

### Eliminar una cita
DELETE http://{{{{host}}}}/api/appointments/2024-11-22/18:00
Authorization: token {{token}}
###

### Confirmar una cita
PUT http://{{host}}/api/appointments/confirm/3
Content-Type: application/json
Authorization: token {{token}}

{
    "confirmAppointment": true
}
