@host = localhost:3001
@tokenPrefix = Bearer
@appointmentId = 2
@datetime = '2024-05-03'

# @name login
POST http://{{host}}/api/auth/login
Content-Type: application/json

{
    "username": "newuser2",
    "password": "Asdfghj??a3kl",
    "role": "admin"
}

###
@authToken = {login.response.body.token}
@appointmentId = 1
### Obtener todas las citas
GET http://{{host}}/api/appointments
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Crear una cita
POST http://{{host}}/api/appointments/
Content-Type: application/json
Authorization: {{tokenPrefix}} {{login.response.body.token}}

{
    "date": "2024-05-09",
    "appointmentTime": "{{$datetime 'HH:mm'}}",
    "realAppointmentTime": "{{$datetime 'HH:mm' 1 h}}",
    "available": true,
    "appointment": {
        "confirmAppointment": false,
        "name": "John Doe",
        "reason": "Consultation"
    }
}

### Obtener citas por fecha
GET http://{{host}}/api/appointments/date/{{datetime}}
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Obtener cita por ID
GET http://{{host}}/api/appointments/{{appointmentId}}
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Actualizar una cita
PUT http://{{host}}/api/appointments/{{appointmentId}}
Content-Type: application/json
Authorization: {{tokenPrefix}} {{login.response.body.token}}

{
    "date": "{{$datetime 'YYYY-MM-DD'}}",
    "appointmentTime": "{{$datetime 'HH:mm'}}",
    "realAppointmentTime": "{{$datetime 'HH:mm' 1 h}}",
    "available": true,
    "appointment": {
        "confirmAppointment": true,
        "name": "John Doe Updated",
        "reason": "Follow-up Consultation"
    }
}

### Eliminar una cita por fecha y hora
DELETE http://{{host}}/api/appointments/{{$datetime 'YYYY-MM-DD'}}/{{$datetime 'HH:mm'}}
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Confirmar una cita
PUT http://{{host}}/api/appointments/confirm/{{appointmentId}}
Content-Type: application/json
Authorization: {{tokenPrefix}} {{login.response.body.token}}

{
    "confirmAppointment": true
}

### Obtener citas disponibles
GET http://{{host}}/api/appointments/available
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Obtener citas confirmadas
GET http://{{host}}/api/appointments/confirmed
Authorization: {{tokenPrefix}} {{login.response.body.token}}
