@host = localhost:3001
@tokenPrefix = Bearer

# @name login
POST http://{{host}}/api/auth/login
Content-Type: application/json

{
    "username": "newuser2",
    "password": "Asdfghj??a3kl",
    "role": "admin"
}

###
@authToken = {login.response.body.token}

### Registrar nuevo usuario
POST http://{{host}}/api/auth/register
Content-Type: application/json

{
    "username": "newuser",
    "password": "Asdfghj??a3kl",
    "role": "admin",

}

### Verificar token
GET http://{{host}}/api/auth/verify
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Refrescar token
POST http://{{host}}/api/auth/refresh
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Cerrar sesión
POST http://{{host}}/api/auth/logout
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Cambiar contraseña
PUT http://{{host}}/api/auth/change-password
Content-Type: application/json
Authorization: {{tokenPrefix}} {{login.response.body.token}}

{
    "oldPassword": "Asdfghj??a3kl",
    "newPassword": "NewPassword123!"
}

### Recuperar contraseña
POST http://{{host}}/api/auth/forgot-password
Content-Type: application/json

{
    "username": "asdfghjklleee"
}