@host = localhost:3001
@tokenPrefix = Bearer
@userId = 2
@username = asdfghjklle
@role = admin
@authToken = {login.response.body.token}
# @name login
POST http://{{host}}/api/auth/login
Content-Type: application/json

{
    "username": "newuser",
    "password": "Asdfghj??a3kl",
    "role": "admin"
}

###


### Obtener todos los usuarios
GET http://{{host}}/api/users
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Obtener un usuario por ID
GET http://{{host}}/api/users/{{userId}}
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Obtener un usuario por username
GET http://{{host}}/api/users/username/{{username}}
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Crear un usuario
POST http://{{host}}/api/users
Content-Type: application/json
Authorization: {{tokenPrefix}} {{login.response.body.token}}

{
    "username": "newuser",
    "password": "Asdfghj??a3kl",
    "role": "admin"
}

### Actualizar un usuario por ID
PUT http://{{host}}/api/users/{{userId}}
Content-Type: application/json
Authorization: {{tokenPrefix}} {{login.response.body.token}}

{
    "username": "updateduser",
    "password": "NewPassword123!",
    "role": "user"
}

### Actualizar un usuario por username
PUT http://{{host}}/api/users/username/{{username}}
Content-Type: application/json
Authorization: {{tokenPrefix}} {{login.response.body.token}}

{
    "username": "updatedusername",
    "password": "NewPassword123!",
    "role": "user"
}

### Eliminar un usuario por ID
DELETE http://{{host}}/api/users/{{userId}}
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Eliminar un usuario por username
DELETE http://{{host}}/api/users/username/{{username}}
Authorization: {{tokenPrefix}} {{login.response.body.token}}

### Obtener usuarios por rol
GET http://{{host}}/api/users/role/{{role}}
Authorization: {{tokenPrefix}} {{login.response.body.token}}

