GET http://localhost:3001/api/appointments

###
POST http://localhost:3001/api/appointments
Content-Type: application/json


{
    "date": "2024-11-21",
    "time": "15:00",
    "available": false,
    "appointment": {
        "name": "Jane Doe",
        "reason": "Consultation"
    }
}


###
DELETE http://localhost:3001/api/appointments/2024-11-21/12:00
